homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 60.2257
  longitude: 24.8636
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Helsinki

  customize:
    media_player.plex_web_chrome:
      hidden: true
    media_player.squicast:
      hidden: true
    media_player.speakers:
      hidden: true

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

device_tracker:
 platform: nmap_tracker
 hosts: 192.168.1.1/24
 exclude:
   - 192.168.1.109
   - 192.168.1.108
   - 192.168.1.104
   - 192.168.1.102
   - 192.168.1.103
   - 192.168.1.235   
   - 192.168.1.105
   - 192.168.1.107
   - 192.168.1.112
   - 192.168.1.106
   - 192.168.1.124
 
tradfri:
  host: 192.168.1.108
  api_key: !secret tradfri_key
  allow_tradfri_groups: false

#-- Anturit ---

sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - windSpeed
      - cloudiness
      - precipitation

  - platform: rest
    resource: http://192.168.1.104/api/eqK7cI-0FhcU1ecd4D8uHqZnKPSDOfvZbqlWTbJc/sensors/4
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: 'Olohuoneen valoisuus'
 
  - platform: rest
    resource: http://192.168.1.104/api/eqK7cI-0FhcU1ecd4D8uHqZnKPSDOfvZbqlWTbJc/sensors/2
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Olohuoneen lampotila'

  - platform: rest
    resource: http://192.168.1.104/api/eqK7cI-0FhcU1ecd4D8uHqZnKPSDOfvZbqlWTbJc/sensors/3
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
    name: 'Olohuoneen liiketunnistin'



group: !include groups.yaml
automation: !include automation.yaml
